version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: edms
      POSTGRES_USER: edms
      POSTGRES_PASSWORD: edms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
